### ISSUE TITLE
s/Open-source models/open models/

### ISSUE THREAD

**Issue by IlnarSelimcan** [BaihaiAI/IDP#10]
Hi!

Thanks for this list. https://github.com/BaihaiAI/IDP/blob/main/AIGC/Awesome%20LLMs%20-%20a%20list%20for%20trending%20open%20source%20LLM%20projects.md

At least LLAMA-based models are not open-source though, since they restrict commercial use, whereas the open-source definition https://opensource.org/osd/ says:

```
6. No Discrimination Against Fields of Endeavor

The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.
```

Thus, "open models" maybe, but not open-source.

**Comment by liminniu** [comment]
> 
Thank you so much for the kind comment. Appologize for our probem with the wording. Indeed LLaMA is not yet open source. Based on your experience and knowledge, do you think it would be ok if we change the title into "Foundation model" and add a note that  " LLaMA and LLaMA based model currenly restrict commercial use”?  Thank you !

**Comment by IlnarSelimcan** [comment]
Sounds good!

In the meantime I've learned that LLaMA model includes all steps for reproducing it. That is, it's very likely that someone/some company will reproduce it and release as an open-source model :)
