### ISSUE TITLE
标准规范的纯英文介绍

### ISSUE THREAD

**Issue by chao325** [BaihaiAI/IDP#3]
很棒！标准规范的纯英文介绍，虽然..貌似并不是很适合国人。但我觉得它更适合成为一个“进口的IDE”。没有中文文档，更加增强了国人学习一门外语的动力！

**Comment by liminniu** [comment]
谢谢建议！ 我们后续会陆续完善中文文档！

**Comment by chao325** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
